using PathOfBuilding.Core.Modifiers;
using PathOfBuilding.Core.Skills;

namespace PathOfBuilding.Core.Modifiers.Parsing;

/// <summary>
/// Describes a tag specification used in modifier flag entries.
/// Mirrors the Lua table shapes like { type = "Condition", var = "CriticalStrike" }.
/// </summary>
public record TagSpec(
    string Type,
    string? Var = null,
    string[]? VarList = null,
    bool Neg = false,
    int? SkillType = null,
    string? SkillName = null,
    string[]? SkillNameList = null,
    bool IncludeTransfigured = false,
    string? SlotName = null,
    string[]? SlotNameList = null,
    string? Actor = null,
    uint? ModFlags = null,
    double? Threshold = null,
    string? ThresholdVar = null,
    int? Num = null,
    string? Keyword = null,
    string? SkillId = null,
    string? Stat = null,
    string[]? StatList = null,
    double? Div = null,
    double? Limit = null,
    bool LimitTotal = false,
    bool LimitNegTotal = false,
    double? GlobalLimit = null,
    string? GlobalLimitKey = null,
    double? Base = null,
    bool NoFloor = false,
    bool Invert = false,
    bool Upper = false,
    bool Equals_ = false,
    double? Percent = null,
    string? ThresholdStat = null,
    string? ItemSlot = null,
    SkillType? SkillTypeValue = null,
    bool? ShaperCond = null,
    bool? ElderCond = null,
    bool? CorruptedCond = null,
    string? SearchCond = null,
    bool BothSlots = false,
    bool AllSlots = false,
    bool ExcludeSelf = false
);

/// <summary>
/// A single entry from the modFlagList or preFlagList tables.
/// Captures all the flags, keyword flags, minion data, tags, and other properties
/// that can appear in a modifier flag entry.
/// </summary>
public record ModFlagEntry(
    ModFlag Flags = ModFlag.None,
    KeywordFlag KeywordFlags = KeywordFlag.None,
    bool AddToMinion = false,
    string? AddToMinionSkillName = null,
    bool AddToMinionIncludeTransfigured = false,
    int? AddToMinionSkillType = null,
    bool ApplyToEnemy = false,
    bool ActorEnemy = false,
    string? ModSuffix = null,
    bool AddToAura = false,
    bool NewAura = false,
    bool NewAuraOnlyAllies = false,
    bool OnlyAddToBanners = false,
    List<TagSpec>? Tags = null,
    List<TagSpec>? PlayerTags = null,
    TagSpec? AddToSkill = null
);

/// <summary>
/// Static data tables ported from ModParser.lua modFlagList (lines 846-1032) and
/// preFlagList (lines 1035-1247).
/// </summary>
public static class ModFlagData
{
    /// <summary>
    /// Plain-text lookup for modifier flags that appear as suffixes in modifier descriptions.
    /// Keys are lowercase. Uses case-insensitive comparison.
    /// Ported from ModParser.lua modFlagList (lines 846-1032).
    /// </summary>
    public static readonly Dictionary<string, ModFlagEntry> ModFlagList = new(StringComparer.OrdinalIgnoreCase)
    {
        // Weapon types
        ["with axes"] = new(Flags: ModFlag.Axe | ModFlag.Hit),
        ["to axe attacks"] = new(Flags: ModFlag.Axe | ModFlag.Hit),
        ["with axe attacks"] = new(Flags: ModFlag.Axe | ModFlag.Hit),
        ["with axes or swords"] = new(Flags: ModFlag.Hit, Tags: [new TagSpec("ModFlagOr", ModFlags: (uint)(ModFlag.Axe | ModFlag.Sword))]),
        ["with bows"] = new(Flags: ModFlag.Bow | ModFlag.Hit),
        ["to bow attacks"] = new(Flags: ModFlag.Bow | ModFlag.Hit),
        ["with bow attacks"] = new(Flags: ModFlag.Bow | ModFlag.Hit),
        ["with claws"] = new(Flags: ModFlag.Claw | ModFlag.Hit),
        ["with claws or daggers"] = new(Flags: ModFlag.Hit, Tags: [new TagSpec("ModFlagOr", ModFlags: (uint)(ModFlag.Claw | ModFlag.Dagger))]),
        ["to claw attacks"] = new(Flags: ModFlag.Claw | ModFlag.Hit),
        ["with claw attacks"] = new(Flags: ModFlag.Claw | ModFlag.Hit),
        ["claw attacks"] = new(Flags: ModFlag.Claw | ModFlag.Hit),
        ["dealt with claws"] = new(Flags: ModFlag.Claw | ModFlag.Hit),
        ["with daggers"] = new(Flags: ModFlag.Dagger | ModFlag.Hit),
        ["to dagger attacks"] = new(Flags: ModFlag.Dagger | ModFlag.Hit),
        ["with dagger attacks"] = new(Flags: ModFlag.Dagger | ModFlag.Hit),
        ["with maces"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["to mace attacks"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["with mace attacks"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["with maces and sceptres"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["with maces or sceptres"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["with maces, sceptres or staves"] = new(Flags: ModFlag.Hit, Tags: [new TagSpec("ModFlagOr", ModFlags: (uint)(ModFlag.Mace | ModFlag.Staff))]),
        ["to mace and sceptre attacks"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["to mace or sceptre attacks"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["with mace or sceptre attacks"] = new(Flags: ModFlag.Mace | ModFlag.Hit),
        ["with staves"] = new(Flags: ModFlag.Staff | ModFlag.Hit),
        ["to staff attacks"] = new(Flags: ModFlag.Staff | ModFlag.Hit),
        ["with staff attacks"] = new(Flags: ModFlag.Staff | ModFlag.Hit),
        ["with swords"] = new(Flags: ModFlag.Sword | ModFlag.Hit),
        ["to sword attacks"] = new(Flags: ModFlag.Sword | ModFlag.Hit),
        ["with sword attacks"] = new(Flags: ModFlag.Sword | ModFlag.Hit),
        ["with wands"] = new(Flags: ModFlag.Wand | ModFlag.Hit),
        ["to wand attacks"] = new(Flags: ModFlag.Wand | ModFlag.Hit),
        ["with wand attacks"] = new(Flags: ModFlag.Wand | ModFlag.Hit),
        ["unarmed"] = new(Flags: ModFlag.Unarmed | ModFlag.Hit),
        ["unarmed melee"] = new(Flags: ModFlag.Unarmed | ModFlag.Melee | ModFlag.Hit),
        ["with unarmed attacks"] = new(Flags: ModFlag.Unarmed | ModFlag.Hit),
        ["with unarmed melee attacks"] = new(Flags: ModFlag.Unarmed | ModFlag.Melee),
        ["with unarmed melee attack"] = new(Flags: ModFlag.Unarmed | ModFlag.Melee),
        ["to unarmed attacks"] = new(Flags: ModFlag.Unarmed | ModFlag.Hit),
        ["to unarmed melee hits"] = new(Flags: ModFlag.Unarmed | ModFlag.Melee | ModFlag.Hit),
        ["with melee weapons"] = new(Flags: ModFlag.WeaponMelee),
        ["with melee weapon attacks"] = new(Flags: ModFlag.WeaponMelee),
        ["from melee weapons"] = new(Flags: ModFlag.WeaponMelee),
        ["from melee weapon attacks"] = new(Flags: ModFlag.WeaponMelee | ModFlag.Hit),
        ["melee weapon"] = new(Flags: ModFlag.WeaponMelee),
        ["with one handed weapons"] = new(Flags: ModFlag.Weapon1H | ModFlag.Hit),
        ["with one handed melee weapons"] = new(Flags: ModFlag.Weapon1H | ModFlag.WeaponMelee | ModFlag.Hit),
        ["with two handed weapons"] = new(Flags: ModFlag.Weapon2H | ModFlag.Hit),
        ["with two handed melee weapons"] = new(Flags: ModFlag.Weapon2H | ModFlag.WeaponMelee | ModFlag.Hit),
        ["with ranged weapons"] = new(Flags: ModFlag.WeaponRanged | ModFlag.Hit),

        // Skill types
        ["spell"] = new(Flags: ModFlag.Spell),
        ["for spells"] = new(Flags: ModFlag.Spell),
        ["for spell damage"] = new(Flags: ModFlag.Spell),
        ["with spell damage"] = new(Flags: ModFlag.Spell),
        ["with spells"] = new(KeywordFlags: KeywordFlag.Spell),
        ["with spell skills"] = new(KeywordFlags: KeywordFlag.Spell),
        ["with triggered spells"] = new(KeywordFlags: KeywordFlag.Spell, Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Triggered)]),
        ["by spells"] = new(KeywordFlags: KeywordFlag.Spell),
        ["by your spells"] = new(KeywordFlags: KeywordFlag.Spell),
        ["with attacks"] = new(KeywordFlags: KeywordFlag.Attack),
        ["by attacks"] = new(KeywordFlags: KeywordFlag.Attack),
        ["by your attacks"] = new(KeywordFlags: KeywordFlag.Attack),
        ["with attack skills"] = new(KeywordFlags: KeywordFlag.Attack),
        ["for attacks"] = new(Flags: ModFlag.Attack),
        ["for attack damage"] = new(Flags: ModFlag.Attack),
        ["weapon"] = new(Flags: ModFlag.Weapon),
        ["with weapons"] = new(Flags: ModFlag.Weapon),
        ["melee"] = new(Flags: ModFlag.Melee),
        ["with melee attacks"] = new(Flags: ModFlag.Melee),
        ["with melee critical strikes"] = new(Flags: ModFlag.Melee, Tags: [new TagSpec("Condition", Var: "CriticalStrike")]),
        ["with melee skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Melee)]),
        ["with bow skills"] = new(KeywordFlags: KeywordFlag.Bow),
        ["on melee hit"] = new(Flags: ModFlag.Melee | ModFlag.Hit),
        ["on hit"] = new(Flags: ModFlag.Hit),
        ["with hits"] = new(KeywordFlags: KeywordFlag.Hit),
        ["with hits against nearby enemies"] = new(KeywordFlags: KeywordFlag.Hit),
        ["with hits and ailments"] = new(KeywordFlags: KeywordFlag.Hit | KeywordFlag.Ailment),
        ["with ailments"] = new(Flags: ModFlag.Ailment),
        ["with ailments from attack skills"] = new(Flags: ModFlag.Ailment, KeywordFlags: KeywordFlag.Attack),
        ["with poison"] = new(KeywordFlags: KeywordFlag.Poison),
        ["with bleeding"] = new(KeywordFlags: KeywordFlag.Bleed),
        ["for ailments"] = new(Flags: ModFlag.Ailment),
        ["for poison"] = new(KeywordFlags: KeywordFlag.Poison | KeywordFlag.MatchAll),
        ["for bleeding"] = new(KeywordFlags: KeywordFlag.Bleed),
        ["for ignite"] = new(KeywordFlags: KeywordFlag.Ignite),
        ["against damage over time"] = new(Flags: ModFlag.Dot),
        ["area"] = new(Flags: ModFlag.Area),
        ["mine"] = new(KeywordFlags: KeywordFlag.Mine),
        ["with mines"] = new(KeywordFlags: KeywordFlag.Mine),
        ["trap"] = new(KeywordFlags: KeywordFlag.Trap),
        ["with traps"] = new(KeywordFlags: KeywordFlag.Trap),
        ["for traps"] = new(KeywordFlags: KeywordFlag.Trap),
        ["skills which throw traps have"] = new(KeywordFlags: KeywordFlag.Trap),
        ["that place mines or throw traps"] = new(KeywordFlags: KeywordFlag.Mine | KeywordFlag.Trap),
        ["that throw mines"] = new(KeywordFlags: KeywordFlag.Mine),
        ["that throw traps"] = new(KeywordFlags: KeywordFlag.Trap),
        ["brand"] = new(KeywordFlags: KeywordFlag.Brand),
        ["totem"] = new(KeywordFlags: KeywordFlag.Totem),
        ["with totem skills"] = new(KeywordFlags: KeywordFlag.Totem),
        ["for skills used by totems"] = new(KeywordFlags: KeywordFlag.Totem),
        ["totem skills that cast an aura"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura)], KeywordFlags: KeywordFlag.Totem),
        ["aura skills that summon totems"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura)], KeywordFlags: KeywordFlag.Totem),
        ["of aura skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura)]),
        ["curse skills"] = new(KeywordFlags: KeywordFlag.Curse),
        ["of curse skills"] = new(KeywordFlags: KeywordFlag.Curse),
        ["with curse skills"] = new(KeywordFlags: KeywordFlag.Curse),
        ["of curse aura skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura)], KeywordFlags: KeywordFlag.Curse),
        ["of curse auras"] = new(KeywordFlags: KeywordFlag.Curse | KeywordFlag.Aura | KeywordFlag.MatchAll),
        ["of hex skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Hex)]),
        ["with hex skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Hex)]),
        ["by retaliation skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Retaliation)]),
        ["of herald skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Herald)]),
        ["with herald skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Herald)]),
        ["with hits from herald skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Herald)], KeywordFlags: KeywordFlag.Hit),
        ["minion skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Minion)]),
        ["with minion skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Minion)]),
        ["of minion skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Minion)]),
        ["link skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Link)]),
        ["of link skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Link)]),
        ["for curses"] = new(KeywordFlags: KeywordFlag.Curse),
        ["for hexes"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Hex)]),
        ["warcry"] = new(KeywordFlags: KeywordFlag.Warcry),
        ["vaal"] = new(KeywordFlags: KeywordFlag.Vaal),
        ["vaal skill"] = new(KeywordFlags: KeywordFlag.Vaal),
        ["with vaal skills"] = new(KeywordFlags: KeywordFlag.Vaal),
        ["with non-vaal skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Vaal, Neg: true)]),
        ["with movement skills"] = new(KeywordFlags: KeywordFlag.Movement),
        ["of movement skills"] = new(KeywordFlags: KeywordFlag.Movement),
        ["of movement skills used"] = new(KeywordFlags: KeywordFlag.Movement),
        ["of travel skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Travel)]),
        ["of banner skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Banner)]),
        ["lightning skills"] = new(KeywordFlags: KeywordFlag.Lightning),
        ["with lightning skills"] = new(KeywordFlags: KeywordFlag.Lightning),
        ["with cold skills"] = new(KeywordFlags: KeywordFlag.Cold),
        ["with fire skills"] = new(KeywordFlags: KeywordFlag.Fire),
        ["with elemental skills"] = new(KeywordFlags: KeywordFlag.Lightning | KeywordFlag.Cold | KeywordFlag.Fire),
        ["with chaos skills"] = new(KeywordFlags: KeywordFlag.Chaos),
        ["with physical skills"] = new(KeywordFlags: KeywordFlag.Physical),
        ["with channelling skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel)]),
        ["channelling"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel)]),
        ["channelling skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel)]),
        ["non-channelling"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel, Neg: true)]),
        ["non-channelling skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel, Neg: true)]),
        ["with brand skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Brand)]),
        ["for stance skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Stance)]),
        ["of stance skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Stance)]),
        ["mark skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Mark)]),
        ["of mark skills"] = new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Mark)]),
        ["with skills that cost life"] = new(Tags: [new TagSpec("StatThreshold", Stat: "LifeCost", Threshold: 1)]),

        // Minion types
        ["minion"] = new(AddToMinion: true),
        ["zombie"] = new(AddToMinion: true, AddToMinionSkillName: "Raise Zombie", AddToMinionIncludeTransfigured: true),
        ["raised zombie"] = new(AddToMinion: true, AddToMinionSkillName: "Raise Zombie", AddToMinionIncludeTransfigured: true),
        ["skeleton"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Skeletons", AddToMinionIncludeTransfigured: true),
        ["spectre"] = new(AddToMinion: true, AddToMinionSkillName: "Raise Spectre", AddToMinionIncludeTransfigured: true),
        ["raised spectre"] = new(AddToMinion: true, AddToMinionSkillName: "Raise Spectre", AddToMinionIncludeTransfigured: true),
        ["golem"] = new(AddToMinion: true, AddToMinionSkillType: (int)Skills.SkillType.Golem),
        ["chaos golem"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Chaos Golem", AddToMinionIncludeTransfigured: true),
        ["flame golem"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Flame Golem", AddToMinionIncludeTransfigured: true),
        ["increased flame golem"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Flame Golem", AddToMinionIncludeTransfigured: true),
        ["ice golem"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Ice Golem", AddToMinionIncludeTransfigured: true),
        ["lightning golem"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Lightning Golem", AddToMinionIncludeTransfigured: true),
        ["stone golem"] = new(AddToMinion: true, AddToMinionSkillName: "Summon Stone Golem", AddToMinionIncludeTransfigured: true),
        ["animated guardian"] = new(AddToMinion: true, AddToMinionSkillName: "Animate Guardian", AddToMinionIncludeTransfigured: true),

        // Damage types
        ["with physical damage"] = new(Tags: [new TagSpec("Condition", Var: "PhysicalHasDamage")]),
        ["with lightning damage"] = new(Tags: [new TagSpec("Condition", Var: "LightningHasDamage")]),
        ["with cold damage"] = new(Tags: [new TagSpec("Condition", Var: "ColdHasDamage")]),
        ["with fire damage"] = new(Tags: [new TagSpec("Condition", Var: "FireHasDamage")]),
        ["with chaos damage"] = new(Tags: [new TagSpec("Condition", Var: "ChaosHasDamage")]),

        // Other
        ["global"] = new(Tags: [new TagSpec("Global")]),
        ["from equipped shield"] = new(Tags: [new TagSpec("SlotName", SlotName: "Weapon 2")]),
        ["from equipped armour items"] = new(Tags: [new TagSpec("SlotName", SlotNameList: ["Helmet", "Body Armour", "Gloves", "Boots", "Weapon 2"])]),
        ["from equipped helmet"] = new(Tags: [new TagSpec("SlotName", SlotName: "Helmet")]),
        ["from equipped gloves and boots"] = new(Tags: [new TagSpec("SlotName", SlotNameList: ["Gloves", "Boots"])]),
        ["from equipped boots and gloves"] = new(Tags: [new TagSpec("SlotName", SlotNameList: ["Gloves", "Boots"])]),
        ["from equipped helmet and gloves"] = new(Tags: [new TagSpec("SlotName", SlotNameList: ["Helmet", "Gloves"])]),
        ["from equipped helmet and boots"] = new(Tags: [new TagSpec("SlotName", SlotNameList: ["Helmet", "Boots"])]),
        ["from your equipped body armour"] = new(Tags: [new TagSpec("SlotName", SlotName: "Body Armour")]),
        ["from equipped body armour"] = new(Tags: [new TagSpec("SlotName", SlotName: "Body Armour")]),
        ["from body armour"] = new(Tags: [new TagSpec("SlotName", SlotName: "Body Armour")]),
        ["from your body armour"] = new(Tags: [new TagSpec("SlotName", SlotName: "Body Armour")]),
    };

    /// <summary>
    /// Regex-pattern lookup for modifier flags that appear at the start of a modifier line.
    /// Patterns are checked in order; the first match wins.
    /// Ported from ModParser.lua preFlagList (lines 1035-1247).
    /// Functional entries (lines 1183-1203) are skipped in this initial port.
    /// </summary>
    public static readonly (string Pattern, ModFlagEntry Entry)[] PreFlagList =
    [
        // Weapon types
        (@"^axe attacks [hd][ae][va][el] ", new(Flags: ModFlag.Axe)),
        (@"^axe or sword attacks [hd][ae][va][el] ", new(Tags: [new TagSpec("ModFlagOr", ModFlags: (uint)(ModFlag.Axe | ModFlag.Sword))])),
        (@"^bow attacks [hd][ae][va][el] ", new(Flags: ModFlag.Bow)),
        (@"^claw attacks [hd][ae][va][el] ", new(Flags: ModFlag.Claw)),
        (@"^claw or dagger attacks [hd][ae][va][el] ", new(Tags: [new TagSpec("ModFlagOr", ModFlags: (uint)(ModFlag.Claw | ModFlag.Dagger))])),
        (@"^dagger attacks [hd][ae][va][el] ", new(Flags: ModFlag.Dagger)),
        (@"^mace or sceptre attacks [hd][ae][va][el] ", new(Flags: ModFlag.Mace)),
        (@"^mace, sceptre or staff attacks [hd][ae][va][el] ", new(Tags: [new TagSpec("ModFlagOr", ModFlags: (uint)(ModFlag.Mace | ModFlag.Staff))])),
        (@"^staff attacks [hd][ae][va][el] ", new(Flags: ModFlag.Staff)),
        (@"^sword attacks [hd][ae][va][el] ", new(Flags: ModFlag.Sword)),
        (@"^wand attacks [hd][ae][va][el] ", new(Flags: ModFlag.Wand)),
        (@"^unarmed attacks [hd][ae][va][el] ", new(Flags: ModFlag.Unarmed)),
        (@"^attacks with one handed weapons [hd][ae][va][el] ", new(Flags: ModFlag.Weapon1H)),
        (@"^attacks with two handed weapons [hd][ae][va][el] ", new(Flags: ModFlag.Weapon2H)),
        (@"^attacks with melee weapons [hd][ae][va][el] ", new(Flags: ModFlag.WeaponMelee)),
        (@"^melee weapon hits [hd][ae][va][el] ", new(Flags: ModFlag.WeaponMelee | ModFlag.Hit)),
        (@"^attacks with one handed melee weapons [hd][ae][va][el] ", new(Flags: ModFlag.Weapon1H | ModFlag.WeaponMelee)),
        (@"^attacks with two handed melee weapons [hd][ae][va][el] ", new(Flags: ModFlag.Weapon2H | ModFlag.WeaponMelee)),
        (@"^attacks with ranged weapons [hd][ae][va][el] ", new(Flags: ModFlag.WeaponRanged)),

        // Damage types
        (@"^attack damage ", new(Flags: ModFlag.Attack)),
        (@"^hits deal ", new(KeywordFlags: KeywordFlag.Hit)),
        (@"^melee weapon damage", new(Flags: ModFlag.WeaponMelee)),
        (@"^deal ", new()),
        (@"^arrows deal ", new(Flags: ModFlag.Bow)),
        (@"^critical strikes deal ", new(Tags: [new TagSpec("Condition", Var: "CriticalStrike")])),
        (@"^poisons you inflict with critical strikes have ", new(KeywordFlags: KeywordFlag.Poison | KeywordFlag.MatchAll, Tags: [new TagSpec("Condition", Var: "CriticalStrike")])),

        // Add to minion
        (@"^minions ", new(AddToMinion: true)),
        (@"^minions [hd][ae][va][el] ", new(AddToMinion: true)),
        (@"^while a unique enemy is in your presence, minions [hd][ae][va][el] ", new(AddToMinion: true, PlayerTags: [new TagSpec("ActorCondition", Actor: "enemy", Var: "RareOrUnique")])),
        (@"^while a pinnacle atlas boss is in your presence, minions [hd][ae][va][el] ", new(AddToMinion: true, PlayerTags: [new TagSpec("ActorCondition", Actor: "enemy", Var: "PinnacleBoss")])),
        (@"^minions leech ", new(AddToMinion: true)),
        (@"^minions' attacks deal ", new(AddToMinion: true, Flags: ModFlag.Attack)),
        (@"^minions created recently have ", new(AddToMinion: true, PlayerTags: [new TagSpec("Condition", Var: "MinionsCreatedRecently")])),
        (@"^golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillType: (int)Skills.SkillType.Golem)),
        (@"^summoned golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillType: (int)Skills.SkillType.Golem)),
        (@"^golem skills have ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Golem)])),
        (@"^zombies [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Raise Zombie", AddToMinionIncludeTransfigured: true)),
        (@"^raised zombies [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Raise Zombie", AddToMinionIncludeTransfigured: true)),
        (@"^skeletons [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Skeletons", AddToMinionIncludeTransfigured: true)),
        (@"^raging spirits [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Raging Spirit", AddToMinionIncludeTransfigured: true)),
        (@"^summoned raging spirits [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Raging Spirit", AddToMinionIncludeTransfigured: true)),
        (@"^r?a?i?s?e?d? ?spectres [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Raise Spectre", AddToMinionIncludeTransfigured: true)),
        (@"^chaos golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Chaos Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned chaos golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Chaos Golem", AddToMinionIncludeTransfigured: true)),
        (@"^flame golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Flame Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned flame golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Flame Golem", AddToMinionIncludeTransfigured: true)),
        (@"^ice golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Ice Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned ice golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Ice Golem", AddToMinionIncludeTransfigured: true)),
        (@"^lightning golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Lightning Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned lightning golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Lightning Golem", AddToMinionIncludeTransfigured: true)),
        (@"^stone golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Stone Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned stone golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Stone Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned carrion golems [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Carrion Golem", AddToMinionIncludeTransfigured: true)),
        (@"^summoned skitterbots [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Carrion Golem", AddToMinionIncludeTransfigured: true)),
        (@"^blink arrow and blink arrow clones [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Blink Arrow", AddToMinionIncludeTransfigured: true)),
        (@"^mirror arrow and mirror arrow clones [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Mirror Arrow", AddToMinionIncludeTransfigured: true)),
        (@"^animated weapons [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Animate Weapon", AddToMinionIncludeTransfigured: true)),
        (@"^animated guardians? deals? ", new(AddToMinion: true, AddToMinionSkillName: "Animate Guardian", AddToMinionIncludeTransfigured: true)),
        (@"^summoned holy relics [hd][ae][va][el] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Holy Relic")),
        (@"^summoned reaper [dh][ea][as]l?s? ", new(AddToMinion: true, AddToMinionSkillName: "Summon Reaper", AddToMinionIncludeTransfigured: true)),
        (@"^summoned arbalists [hgdf][aei][vair][eln] ", new(AddToMinion: true, AddToMinionSkillName: "Summon Arbalists")),
        (@"^summoned arbalists' attacks have ", new(AddToMinion: true, AddToMinionSkillName: "Summon Arbalists")),
        (@"^herald skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Herald)])),
        (@"^agony crawler deals ", new(AddToMinion: true, AddToMinionSkillName: "Herald of Agony")),
        (@"^summoned agony crawler fires ", new(AddToMinion: true, AddToMinionSkillName: "Herald of Agony")),
        (@"^sentinels of purity deal ", new(AddToMinion: true, AddToMinionSkillName: "Herald of Purity")),
        (@"^summoned sentinels of absolution have ", new(AddToMinion: true, AddToMinionSkillName: "Absolution", AddToMinionIncludeTransfigured: true)),
        (@"^summoned sentinels have ", new(AddToMinion: true, AddToMinionSkillName: "Herald of Purity")),
        // Note: Lua line 1106 uses skillNameList for "summoned sentinels have" but ModFlagEntry uses a single AddToMinionSkillName.
        // The Lua entry has skillNameList = { "Herald of Purity", "Dominating Blow", "Absolution" }.
        // This is approximated; a future enhancement may add AddToMinionSkillNameList support.
        (@"^raised zombies' slam attack has ", new(AddToMinion: true, Tags: [new TagSpec("SkillId", SkillId: "ZombieSlam")])),
        (@"^raised spectres, raised zombies, and summoned skeletons have ", new(AddToMinion: true, AddToMinionSkillName: "Raise Spectre", AddToMinionIncludeTransfigured: true)),
        // Note: Lua line 1108 uses skillNameList = { "Raise Spectre", "Raise Zombie", "Summon Skeletons" }.
        // This is approximated; a future enhancement may add AddToMinionSkillNameList support.

        // Totem/trap/mine
        (@"^attacks used by totems have ", new(Flags: ModFlag.Attack, KeywordFlags: KeywordFlag.Totem)),
        (@"^spells cast by totems [hd][ae][va][el] ", new(Flags: ModFlag.Spell, KeywordFlags: KeywordFlag.Totem)),
        (@"^trap and mine damage ", new(KeywordFlags: KeywordFlag.Trap | KeywordFlag.Mine)),
        (@"^skills used by traps [hgd][ae][via][enl] ", new(KeywordFlags: KeywordFlag.Trap)),
        (@"^skills which throw traps [hgd][ae][via][enl] ", new(KeywordFlags: KeywordFlag.Trap)),
        (@"^skills used by mines [hgd][ae][via][enl] ", new(KeywordFlags: KeywordFlag.Mine)),
        (@"^skills which throw mines ([hgd][ae][via][enl])? ", new(KeywordFlags: KeywordFlag.Mine)),
        (@"^skills used by your traps and mines ([hgd]?[ae]?[via]?[enl]?[ ]?)", new(KeywordFlags: KeywordFlag.Trap | KeywordFlag.Mine)),

        // Local damage
        (@"^attacks with this weapon ", new(Tags: [new TagSpec("Condition", Var: "{Hand}Attack"), new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Attack)])),
        (@"^attacks with this weapon [hd][ae][va][el] ", new(Tags: [new TagSpec("Condition", Var: "{Hand}Attack"), new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Attack)])),
        (@"^hits with this weapon [hd][ae][va][el] ", new(Flags: ModFlag.Hit, Tags: [new TagSpec("Condition", Var: "{Hand}Attack"), new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Attack)])),

        // Skill types
        (@"^attacks [hd][ae][va][el] ", new(Flags: ModFlag.Attack)),
        (@"^attack skills [hd][ae][va][el] ", new(KeywordFlags: KeywordFlag.Attack)),
        (@"^spells [hd][ae][va][el] a? ?", new(Flags: ModFlag.Spell)),
        (@"^spell skills [hd][ae][va][el] ", new(KeywordFlags: KeywordFlag.Spell)),
        (@"^projectile attack skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.RangedAttack)])),
        (@"^projectiles from attacks [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.RangedAttack)])),
        (@"^arrows [hd][ae][va][el] ", new(KeywordFlags: KeywordFlag.Bow)),
        (@"^bow skills [hdf][aei][var][el] ", new(KeywordFlags: KeywordFlag.Bow)),
        (@"^projectiles [hdf][aei][var][el] ", new(Flags: ModFlag.Projectile)),
        (@"^projectiles ", new(Flags: ModFlag.Projectile)),
        (@"^melee attacks have ", new(Flags: ModFlag.Melee)),
        (@"^movement attack skills have ", new(Flags: ModFlag.Attack, KeywordFlags: KeywordFlag.Movement)),
        (@"^travel skills have ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Travel)])),
        (@"^link skills have ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Link)])),
        (@"^lightning skills [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Lightning)),
        (@"^lightning spells [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Lightning, Flags: ModFlag.Spell)),
        (@"^cold skills [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Cold)),
        (@"^cold spells [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Cold, Flags: ModFlag.Spell)),
        (@"^fire skills [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Fire)),
        (@"^fire spells [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Fire, Flags: ModFlag.Spell)),
        (@"^chaos skills [hd][ae][va][el] a? ?", new(KeywordFlags: KeywordFlag.Chaos)),
        (@"^vaal skills [hd][ae][va][el] ", new(KeywordFlags: KeywordFlag.Vaal)),
        (@"^vaal skills require ", new(KeywordFlags: KeywordFlag.Vaal)),
        (@"^non-aura vaal skills require ", new(KeywordFlags: KeywordFlag.Vaal, Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura, Neg: true)])),
        (@"^brand skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Brand)])),
        (@"^channelling skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel)])),
        (@"^curse skills [hd][ae][va][el] ", new(KeywordFlags: KeywordFlag.Curse)),
        (@"^hex skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Hex)])),
        (@"^mark skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Mark)])),
        (@"^melee skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Melee)])),
        (@"^guard skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Guard)])),
        (@"^banner skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Banner)])),
        (@"^nova spells [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Nova)])),
        (@"^area skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Area)])),
        (@"^aura skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura)])),
        (@"^prismatic skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.RandomElement)])),
        (@"^retaliation skills [hd][ae][va][el] ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Retaliation)])),
        (@"^warcry skills have ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Warcry)])),
        (@"^non-curse aura skills have ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Aura), new TagSpec("SkillType", SkillType: (int)Skills.SkillType.AppliesCurse, Neg: true)])),
        (@"^non-channelling skills have ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Channel, Neg: true)])),
        (@"^non-vaal skills deal ", new(Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Vaal, Neg: true)])),
        (@"^skills [hgdf][aei][vari][eln] ", new()),

        // Slot specific
        (@"^left ring slot: ", new(Tags: [new TagSpec("SlotNumber", Num: 1)])),
        (@"^right ring slot: ", new(Tags: [new TagSpec("SlotNumber", Num: 2)])),
        (@"^socketed gems ([hgd]?[ae]?[via]?[enl]?\s?)", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}"))),
        (@"^socketed skills [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}"))),
        (@"^socketed travel skills [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "travel"))),
        (@"^socketed warcry skills [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "warcry"))),
        (@"^socketed attacks [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "attack"))),
        (@"^socketed spells [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "spell"))),
        (@"^socketed curse gems [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "curse"))),
        (@"^socketed melee gems [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "melee"))),
        (@"^socketed golem gems [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "golem"))),
        (@"^socketed golem skills [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "golem"))),
        (@"^socketed golem skills have minions ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "golem"))),
        (@"^socketed vaal skills [hgd][ae][via][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}", Keyword: "vaal"))),
        (@"^socketed projectile spells [hgdf][aei][viar][enl] ", new(AddToSkill: new TagSpec("SocketedIn", SlotName: "{SlotName}"), Tags: [new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Projectile), new TagSpec("SkillType", SkillType: (int)Skills.SkillType.Spell)])),

        // Enemy modifiers (static entries only; functional entries from lines 1183-1203 are skipped)
        (@"^enemies withered by you [th]a[vk]e ", new(Tags: [new TagSpec("MultiplierThreshold", Var: "WitheredStack", Threshold: 1)], ApplyToEnemy: true)),
        // Lines 1183-1203: functional entries skipped (need runtime handling)
        (@"^enemies shocked or frozen by you take ", new(Tags: [new TagSpec("Condition", VarList: ["Shocked", "Frozen"])], ApplyToEnemy: true, ModSuffix: "Taken")),
        (@"^enemies affected by your spider's webs [thd][ae][avk][el] ", new(Tags: [new TagSpec("MultiplierThreshold", Var: "Spider's WebStack", Threshold: 1)], ApplyToEnemy: true)),
        (@"^enemies you curse take ", new(Tags: [new TagSpec("Condition", Var: "Cursed")], ApplyToEnemy: true, ModSuffix: "Taken")),
        (@"^enemies you curse ", new(Tags: [new TagSpec("Condition", Var: "Cursed")], ApplyToEnemy: true)),
        (@"^nearby enemies take ", new(ModSuffix: "Taken", ApplyToEnemy: true)),
        (@"^nearby enemies have ", new(ApplyToEnemy: true)),
        (@"^nearby enemies deal ", new(ApplyToEnemy: true)),
        (@"^nearby enemies'? ", new(ApplyToEnemy: true)),
        (@"^nearby enemy monsters' ", new(ApplyToEnemy: true)),
        ("against you", new(ApplyToEnemy: true, ActorEnemy: true)),
        (@"^hits against you ", new(ApplyToEnemy: true, Flags: ModFlag.Hit)),
        (@"^enemies near your totems deal ", new(ApplyToEnemy: true)),

        // Other
        (@"^your flasks grant ", new()),
        (@"^when hit, ", new()),
        (@"^you and allies [hgd][ae][via][enl] ", new()),
        (@"^auras from your skills grant ", new(AddToAura: true)),
        (@"^auras grant ", new(AddToAura: true)),
        (@"^banners also grant ", new(AddToAura: true, OnlyAddToBanners: true)),
        (@"^you and nearby allies ", new(NewAura: true)),
        (@"^you and nearby allies [hgd][ae][via][enl] ", new(NewAura: true)),
        (@"^nearby allies [hgd][ae][via][enl] ", new(NewAura: true, NewAuraOnlyAllies: true)),
        (@"^every rage also grants ", new(Tags: [new TagSpec("Multiplier", Var: "RageEffect")])),
        (@"^each rage also grants ", new(Tags: [new TagSpec("Multiplier", Var: "RageEffect")])),
        (@"^you and allies affected by auras from your skills [hgd][ae][via][enl] ", new(Tags: [new TagSpec("Condition", Var: "AffectedByAura")])),
        (@"^take ", new(ModSuffix: "Taken")),
        (@"^marauder: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToMarauderStart")])),
        (@"^duelist: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToDuelistStart")])),
        (@"^ranger: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToRangerStart")])),
        (@"^shadow: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToShadowStart")])),
        (@"^witch: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToWitchStart")])),
        (@"^templar: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToTemplarStart")])),
        (@"^scion: ", new(Tags: [new TagSpec("Condition", Var: "ConnectedToScionStart")])),
        (@"^skills supported by spellslinger have ", new(Tags: [new TagSpec("Condition", Var: "SupportedBySpellslinger")])),
        (@"^skills that have dealt a critical strike in the past 8 seconds deal ", new(Tags: [new TagSpec("Condition", Var: "CritInPast8Sec")])),
        (@"^blink arrow and mirror arrow have ", new(Tags: [new TagSpec("SkillName", SkillNameList: ["Blink Arrow", "Mirror Arrow"], IncludeTransfigured: true)])),
        ("attacks with energy blades ", new(Flags: ModFlag.Attack, Tags: [new TagSpec("Condition", Var: "AffectedByEnergyBlade")])),
        (@"^for each nearby corpse, ", new(Tags: [new TagSpec("Multiplier", Var: "NearbyCorpse")])),
        (@"^enemies in your link beams have ", new(Tags: [new TagSpec("Condition", Var: "BetweenYouAndLinkedTarget")], ApplyToEnemy: true)),
        (@"^consecrated ground you create a?l?s?o? ?grants ", new(Tags: [new TagSpec("Condition", Var: "OnConsecratedGround")])),

        // While in the presence of...
        (@"^while a unique enemy is in your presence, ", new(Tags: [new TagSpec("ActorCondition", Actor: "enemy", Var: "RareOrUnique")])),
        (@"^while a pinnacle atlas boss is in your presence, ", new(Tags: [new TagSpec("ActorCondition", Actor: "enemy", Var: "PinnacleBoss")])),
    ];
}
